version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "15432:3306"        # ホスト15432 → コンテナ3306

  web:
    build: .
    working_dir: /usr/src/app          # Dockerfile と合わせる
    command: bash -c "rm -f tmp/pids/server.pid \
      && bundle exec puma -C config/puma.rb"
    # command: bundle exec rails s -b 0.0.0.0 -p 3000
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/usr/src/app/node_modules
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome

  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"

volumes:
  mysql_data:
  bundle_data:
  node_modules:
