# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.3'

gem 'bootsnap', require: false
gem 'importmap-rails'
gem 'jbuilder'
gem 'pg'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2.2', '>= 7.2.2.1'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'letter_opener_web', '2.0.0'
  gem 'web-console'
end

group :development, :test do
  # MySQL ドライバ（ローカル開発・テスト用）
  # gem "mysql2", ">= 0.5.3", "< 0.6.0"
  # もしテストで sqlite3 を使いたければ残しても OK
  gem 'brakeman', require: false
  gem 'capybara'
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'dotenv-rails'
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rails-omakase', require: false
  gem 'selenium-webdriver'
  gem 'sqlite3'
end

group :production do
  # Heroku 本番では Postgres を使う
  # gem "pg"
end

gem 'config'
gem 'rails-i18n', '~> 7.0'
gem 'sorcery', '0.16.3'
# esbuildから移行
# gem "jsbundling-rails", "~> 1.3"
# deviseでsnsログイン用
# gem 'omniauth'
# gem 'omniauth-google-oauth2'
# gem 'omniauth-rails_csrf_protection'

# CORS設定
gem 'rack-cors'

gem 'devise'
gem 'devise-jwt'

gem 'resend'
gem 'sendgrid-actionmailer'
gem 'sendgrid-ruby'
