default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: db
  username: root
  password: password
  socket: 

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  # Heroku 本番では DATABASE_URL を使う
  url: <%= ENV["DATABASE_URL"] %>
