default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["MYSQL_USER"] || "root" %>
  password: <%= ENV["MYSQL_PASSWORD"] || "password" %>
  host: <%= ENV["MYSQL_HOST"] || "db" %>
  port: <%= ENV["MYSQL_PORT"] || 3306 %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  host: mysql
  database: app_test

production:
  <<: *default
  # 本番だけ Heroku や Render の DATABASE_URL を使用（※mysql対応DBサービスの場合）
  url: <%= ENV["DATABASE_URL"] if ENV["DATABASE_URL"]&.include?("mysql2") %>
  database: <%= ENV["MYSQL_DATABASE"] || "app_production" %>
